### ISSUE TITLE
Filter log formatter error

### ISSUE THREAD

**Issue by cubedro** [ethereum/ethereum.js#148]
I've got 2 filters: pending and chain:
```
{ jsonrpc: '2.0',
  method: 'eth_newBlockFilter',
  params: [ 'pending' ],
  id: 45 }
{"id":45,"jsonrpc":"2.0","result":"0x0"}

{ jsonrpc: '2.0',
  method: 'eth_newBlockFilter',
  params: [ 'latest' ],
  id: 46 }
{"id":46,"jsonrpc":"2.0","result":"0x1"}
```

Here's the request & response:
```
[ { jsonrpc: '2.0',
    method: 'eth_getFilterChanges',
    params: [ '0x0' ],
    id: 509 },
  { jsonrpc: '2.0',
    method: 'eth_getFilterChanges',
    params: [ '0x1' ],
    id: 510 } ]
[ { id: 509, jsonrpc: '2.0', result: [ null ] },
  { id: 510, jsonrpc: '2.0', result: [ null ] } ]
```

And this is the error thrown:
```
/Users/Cubu/Documents/Web/ethereum/eth-net-intelligence-api/node_modules/ethereum.js/lib/web3/formatters.js:136
    log.blockNumber = utils.toDecimal(log.blockNumber);
                                         ^
TypeError: Cannot read property 'blockNumber' of null
    at outputLogFormatter [as formatter] (/Users/Cubu/Documents/Web/ethereum/eth-net-intelligence-api/node_modules/ethereum.js/lib/web3/formatters.js:136:42)
    at /Users/Cubu/Documents/Web/ethereum/eth-net-intelligence-api/node_modules/ethereum.js/lib/web3/filter.js:91:45
```

**Comment by caktux** [comment]
also having problems with filter.js, `undefined is not a function` at line 43

**Comment by debris** [comment]
Will be fixed with proper test case today

**Comment by caktux** [comment]
thanks, 0.2.0 is unusable right now

**Comment by debris** [comment]
@cubedro should be working fine now. I also fixed the test, that was checking if it is working properly.
